### ISSUE TITLE
Small `venv` quirk

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#14]
If I clone @henryleberre 's fork and issue `./mfc.sh` I immediately get:

```
[I]shb-m1pro: Downloads/MFC $ ./mfc.sh
./mfc.sh: line 223: /Users/spencer/Downloads/MFC/build/venv/bin/activate: No such file or directory
Collecting pyyaml
  Using cached PyYAML-6.0-cp310-cp310-macosx_11_0_arm64.whl (173 kB)
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0
Collecting rich
  Using cached rich-12.5.1-py3-none-any.whl (235 kB)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Users/spencer/Library/Python/3.10/lib/python/site-packages (from rich) (2.13.0)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Installing collected packages: commonmark, rich
Successfully installed commonmark-0.9.1 rich-12.5.1
Collecting fypp
  Using cached fypp-3.1-py3-none-any.whl
Installing collected packages: fypp
Successfully installed fypp-3.1
usage: ./mfc.sh [-h] {run,test,build,clean} ...

Wecome to the MFC master script. This tool automates and manages building, testing, running, and cleaning of MFC in various configurations on
all supported platforms. The README documents this tool and its various commands in more detail. To get started, run ./mfc.sh build -h.
```

Thus, it still works fine (seemingly, as aside from the 'Wecome' typo), but it lets out a warning on the first stdout line. It didn't do this a few weeks ago, so it's a new change I believe.

It does the same thing on subsequent `mfc.sh` calls.

**Comment by henryleberre** [comment]
@sbryngelson That typo is indeed quite embarrassing... Many strings of text within `mfc.sh` rarely get printed because they are associated with unlikely errors/events, so it can be hard at times to spot these kinds of typos.

The `venv` warning is caused by `mfc.sh` attempting to enter the `venv` but failing to locate the `build/venv/bin/activate` script. My best guess is that you `CTRL + C`'d while it was installing the `venv`, causing it to stop halfway through. Since it had created the `venv` folder, `mfc.sh` assumed it was installed, and that `build/venv/bin/activate` was present. I couldn't reproduce your issue by just cloning and running `./mfc.sh`.

To attempt and mitigate this issue, I made it check for the existence of `build/venv/bin/activate` instead of just `build/venv/`.

**Comment by sbryngelson** [comment]
Yes this is exactly what happened. Thanks!
