### ISSUE TITLE
Issue running `./mfc.sh test` on Phoenix

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#160]
This issue is mostly the same as this one: https://github.com/MFlowCode/MFC/issues/143

Where when on an interactive node, I get the same error:
```console
Error: Test tests/D79C3E6F: 1D -> bc=-1: Line count didn't match.
```

I've tried using different `salloc` commands, like `-N 1 --ntasks-per-node=1` and `-N 1 -n 1`, but these doesn't seem to help. I have also tried using `-b mpirun` and `-b srun`, but both have problems.

I can successfully run a test from a login node, which submits the job some other way. It seems like  @henryleberre 's https://github.com/MFlowCode/MFC/pull/146 was supposed to fix this via OpenMPI, but the issue appears to be back (or maybe never completely worked in the first place... or I just didn't understand it).

This issue isn't mission-critical and I won't label it a "bug," but it seems like getting to the bottom of this more comprehensively will also be useful for others. Presumably, many are doing interactive testing.

**Comment by anandrdbz** [comment]
@sbryngelson you can run it using the following commands: 

salloc -N 1 -n 2 (Get 1 node with 2 ranks since one of the tests uses 2 ranks)

./mfc.sh test -b mpirun 

I used this and got all the tests to pass

You cannot use srun inside an interactive node since this causes a contradiction with --ntasks-per-node parameter. And the reason why mpirun failed for you is because you launched srun initially, which can incorrectly create extra files in D folder (as it launches the job with more than 1 rank), leading to a line count mismatch. So if you do incorrectly launch it with srun once, you'd have to clear the data files before launching it with mpirun 

So simply run rm -rf tests/*/D/* and rm -rf tests/*/p_all/* before running ./mfc.sh test -b mpirun and you should be good

**Comment by sbryngelson** [comment]
Thanks @anandrdbz
