### ISSUE TITLE
`p_main` is become long and confusing

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#184]
The `p_main.fpp` file is becoming long and confusing. This is the entry point to the main part of the code for almost all new users, so we should make it as easy to digest as possible. 

Possibilities for improvement are below. All of these changes would have effectively zero computational cost.

https://github.com/anandrdbz/MFC/blob/6da8a3c618d596e91b9194cd8c81bb7f01d41505/src/simulation/p_main.fpp#L235-L328

The above code is the main "time-stepping" loop, and seems like it should be in its own subroutine or function or something.

https://github.com/anandrdbz/MFC/blob/6da8a3c618d596e91b9194cd8c81bb7f01d41505/src/simulation/p_main.fpp#L137-L150

The above code has to do with a small part of the code that most folks won't use. Perhaps it should also live somewhere else, not in this main introductory file?

https://github.com/anandrdbz/MFC/blob/6da8a3c618d596e91b9194cd8c81bb7f01d41505/src/simulation/p_main.fpp#L224-L233

There are some snippets like the above related to GPU memory allocation. This is important for the developer but not the user. Can we make this "cleaner" by putting memory allocations closer to where the variable is introduced?

https://github.com/anandrdbz/MFC/blob/6da8a3c618d596e91b9194cd8c81bb7f01d41505/src/simulation/p_main.fpp#L156-L185

The above (and the like) all have the same pattern... `s_initialize_X_module`. Should they not be in their own subroutine?

**Comment by anandrdbz** [comment]
These could all potentially be done in another new file that's not p_main.fpp, and I should be able to do those quite easily. 

The reason some of these calls are not done closer to declaration is because most of these were declared in m_gloabl_parameters.fpp, and the compiler would run into issues with this because m_global_parameters is included in all other modules (like var_conv, m_helper etc) so using those modules in m_global would lead to circular conflicts. 

I can use another new module that uses most of the other modules (including m_global) so that p_main looks more clean to the user.

**Comment by sbryngelson** [comment]
Yes I would be curious to see that.

**Comment by sbryngelson** [comment]
Closed by #183
