### ISSUE TITLE
Doxygen broken with addition of fypp everywhere.

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#82]
**Describe the bug**
Doxygen doesn't recognize fypp files and thus doesn't build documentation for them.

**To Reproduce**
1. Navigate [here](https://mflowcode.github.io/pre_process/namespaces.html)

**Expected behavior**
Documentation should be produced for all source files.
If fypp and Doxygen do not play nicely, one can autogenerate the code and use Doxygen on those files.

**Comment by henryleberre** [comment]
The issue is here:
https://github.com/MFlowCode/MFC/blob/95ac09d3409ccb92de2dc6f67ef9e1f9836f95c0/CMakeLists.txt#L348
I must have changed `_srcs` to be `_SRCs` one day and forgot to update it there. This would have still worked if the documentation action had built the codes because the fpp files would be declared as target dependencies and would have generated F90 files into `src/${target}/autogen`.
